server:
  port: 8082

spring:
  r2dbc:
    url: r2dbc:h2:mem:///test
    username: community
    password: community
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
debug: true
