server:
  port: 8082

spring:
  r2dbc:
    url: r2dbc:h2:mem:///msa;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password:
    initialization-mode: always

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
debug: false
